Repository pattern-lab/patternlab-node, pull requests merged in 2020-08, with the labels that each got.

#1120 Allow using --watch option in patternlab build
  packages/cli/bin/build.js
  packages/cli/bin/patternlab.js
  packages/core/src/lib/patternlab.js
  packages/core/src/lib/watchPatternLabFiles.js
Labels: Approved by Member

#1139 Make sure every uikit is going to be reset when the frontend is build.
  packages/core/src/lib/exportData.js
  packages/core/src/lib/ui_builder.js
  packages/core/test/exportData_tests.js
  packages/plugin-tab/src/snippet.js
  packages/uikit-workshop/src/scripts/components/panels.js
Labels: ready for release 🆗

#1156 improvement: ability to configure default pattern info code panel #1155
  packages/docs/src/docs/advanced-config-options.md
  packages/uikit-workshop/src/scripts/components/panels.js
Labels: ready for review

#1236 Fix too much recursion and update node-sass
  packages/uikit-workshop/package.json
  packages/uikit-workshop/src/scripts/components/pl-nav/pl-nav.js
  packages/uikit-workshop/src/scripts/components/pl-search/pl-search.js
  packages/uikit-workshop/src/scripts/lit-components/pl-drawer/pl-drawer.js
  packages/uikit-workshop/src/scripts/lit-components/pl-toggle-info/pl-toggle-info.js
  packages/uikit-workshop/src/scripts/lit-components/pl-toggle-layout/pl-toggle-layout.js
  packages/uikit-workshop/src/scripts/lit-components/pl-toggle-theme/pl-toggle-theme.js
  packages/uikit-workshop/src/scripts/lit-components/pl-viewport-size-list/pl-viewport-size-list.js
  yarn.lock
Labels: ready for review

#1233 Fix broken nav for too many entries
  packages/uikit-workshop/src/sass/scss/05-themes/_sidebar-theme.scss
  packages/uikit-workshop/src/scripts/components/pl-nav/pl-nav.scss
Labels: ready for review

#1234 Fix unhandled promise rejection on server.open
  packages/live-server/index.js
Labels: ready for review

#1235 Fix live-server injects code to SVGs
  packages/live-server/index.js
Labels: ready for review

#1244 Enable doc tables and fix frontmatter bug
  packages/core/src/lib/markdown_parser.js
  packages/uikit-workshop/src/sass/scss/04-components/_text-passage.scss
Labels: ready for review

#1248 Fixing Dependabot alerts.
  packages/cli/package.json
  packages/core/package.json
  packages/edition-node-gulp/package.json
  packages/plugin-tab/package.json
  yarn.lock
Labels: ready for review

#1246 Loading uikit resources via the Node resolver
  package.json
  packages/cli/bin/install-edition.js
  packages/cli/bin/install-plugin.js
  packages/cli/bin/install-starterkit.js
  packages/cli/bin/utils.js
  packages/core/patternlab-config.json
  packages/core/src/index.js
  packages/core/src/lib/loaduikits.js
  packages/core/src/lib/resolver.js
  packages/core/src/lib/starterkit_manager.js
  packages/core/test/loaduitkits_tests.js
  packages/core/test/util/patternlab-config.json
  packages/development-edition-engine-handlebars/package.json
  packages/development-edition-engine-handlebars/patternlab-config.json
  packages/development-edition-engine-twig/patternlab-config.json
  packages/edition-node-gulp/patternlab-config.json
  packages/edition-node/patternlab-config.json
  packages/edition-twig/patternlab-config.json
Labels: ready for review

#1249 Documenting the `package` tag on `uikits` config entries
  packages/docs/src/docs/advanced-config-options.md
Labels: ready for review

#1254 Remove last traces of `installplugin` from `core` package
  packages/core/docs/README.md
  packages/core/src/index.js
  packages/development-edition-engine-react/gulpfile.js
  packages/edition-node-gulp/gulpfile.js
  yarn.lock
Labels: ready for review
