Repository pattern-lab/patternlab-node, pull requests merged in 2022-12, with the labels that each got.

#1449 refactor: updated CodeQL actions
  .github/workflows/codeql-analysis.yml
Labels: dependencies

#1450 chore: fix HTML structure
  .github/gitgraph/branching-scheme.html
Labels: low priority :zzz:

#1445 chore: defining the latest LTS Node version as the minimum
  .github/ISSUE_TEMPLATE.md
  .nvmrc
  packages/cli/.nvmrc
  packages/cli/package.json
  packages/core/.nvmrc
  packages/core/package.json
  packages/create/package.json
  packages/development-edition-engine-handlebars/.nvmrc
  packages/development-edition-engine-handlebars/package.json
  packages/development-edition-engine-react/.nvmrc
  packages/development-edition-engine-react/package.json
  packages/development-edition-engine-twig/package.json
  packages/docs/package.json
  packages/edition-node-gulp/.nvmrc
  packages/edition-node-gulp/package.json
  packages/edition-node/.nvmrc
  packages/edition-node/package.json
  packages/edition-twig/package.json
  packages/engine-handlebars/.nvmrc
  packages/engine-handlebars/package.json
  packages/engine-liquid/.nvmrc
  packages/engine-liquid/package.json
  packages/engine-mustache/.nvmrc
  packages/engine-mustache/package.json
  packages/engine-nunjucks/.nvmrc
  packages/engine-nunjucks/package.json
  packages/engine-react/.nvmrc
  packages/engine-react/package.json
  packages/engine-twig-php/package.json
  packages/engine-twig/.nvmrc
  packages/engine-twig/package.json
  packages/engine-underscore/.nvmrc
  packages/engine-underscore/package.json
  packages/live-server/.nvmrc
  packages/live-server/package.json
  packages/plugin-tab/.nvmrc
  packages/plugin-tab/package.json
  packages/starterkit-handlebars-demo/package.json
  packages/starterkit-twig-demo/package.json
  packages/uikit-polyfills/package.json
  packages/uikit-workshop/.nvmrc
  packages/uikit-workshop/package.json
Labels: enhancement :sparkles:

#1431 refactor: update dependencies
  package.json
  packages/cli/package.json
  packages/core/package.json
  packages/docs/package.json
  packages/live-server/package.json
  yarn.lock
Labels: dependencies

#1456 refactor: replaced hogan.js by handlebars
  packages/uikit-workshop/package.json
  packages/uikit-workshop/src/scripts/components/panels-viewer.js
  yarn.lock
Labels: dependencies

#1457 refactor: the CLI package needed an update regarding handlebars
  packages/cli/package.json
  packages/cli/readme.md
  packages/cli/test/cli-build.test.js
  packages/cli/test/cli-disable.test.js
  packages/cli/test/cli-enable.test.js
  packages/cli/test/cli-export.test.js
  packages/cli/test/cli-init.test.js
  packages/cli/test/fixtures/patternlab-config.json
  packages/cli/test/install-starterkit.test.js
  packages/starterkit-handlebars-demo/README.md
  yarn.lock
Labels: dependencies

#1461 fix: hogan to handlebars migration leftovers
  packages/uikit-workshop/src/scripts/components/panels-viewer.js
Labels: bug :bug:, uikit

#1463 fix: updated base template to handlebars
  packages/uikit-workshop/src/html/index.html
  packages/uikit-workshop/src/html/partials/base-template.html
Labels: bug :bug:, uikit

#1256 Pattern Lab only loads the pattern engines from the config
  packages/cli/test/fixtures/patternlab-config.json
  packages/core/patternlab-config.json
  packages/core/src/lib/pattern_engines.js
  packages/core/test/util/patternlab-config.json
  packages/development-edition-engine-handlebars/patternlab-config.json
  packages/development-edition-engine-react/patternlab-config.json
  packages/development-edition-engine-twig/patternlab-config.json
  packages/docs/src/docs/advanced-config-options.md
  packages/edition-node-gulp/patternlab-config.json
  packages/edition-node/patternlab-config.json
  packages/edition-twig/patternlab-config.json
  packages/starterkit-twig-demo/patternlab-config.json
Labels: WIP :walking:
