Repository pattern-lab/patternlab-node, pull requests merged in 2023-01, with the labels that each got.

#1465 refactor: replaced hogan by handlebars
  packages/engine-react/lib/engine_react.js
  packages/engine-react/lib/outputTemplate.hbs
  packages/engine-react/lib/outputTemplate.mustache
  packages/engine-react/package.json
  yarn.lock
Labels: dependencies

#1466 chore(cli): optimized logging output
  packages/cli/bin/cli-actions/help.js
Labels: low priority :zzz:, documentation :book:

#1400 refactor: updated dependency commander
  packages/cli/bin/cli-actions/build.js
  packages/cli/bin/cli-actions/disable.js
  packages/cli/bin/cli-actions/enable.js
  packages/cli/bin/cli-actions/export.js
  packages/cli/bin/cli-actions/install.js
  packages/cli/bin/cli-actions/serve.js
  packages/cli/bin/patternlab.js
  packages/cli/package.json
  yarn.lock
Labels: dependencies

#1102 UIKit Nav Cleanup
  packages/docs/src/_data/global.js
  packages/docs/src/filters/date-filter.js
  packages/docs/src/js/components/theme-toggle.js
  packages/docs/src/transforms/html-min-transform.js
  packages/uikit-workshop/package.json
  packages/uikit-workshop/src/sass/pattern-lab.scss
  packages/uikit-workshop/src/sass/scss/04-components/_pattern-states.scss
  packages/uikit-workshop/src/sass/scss/05-themes/_sidebar-theme.scss
  packages/uikit-workshop/src/scripts/components/base-skate-preact-element.js
  packages/uikit-workshop/src/scripts/components/pl-nav/index.scss
  packages/uikit-workshop/src/scripts/components/pl-nav/nav-accordion.scss
  packages/uikit-workshop/src/scripts/components/pl-nav/nav-dropdown.scss
  packages/uikit-workshop/src/scripts/components/pl-nav/nav-link.js
  packages/uikit-workshop/src/scripts/components/pl-nav/nav-link.scss
  packages/uikit-workshop/src/scripts/components/pl-nav/nav-list.js
  packages/uikit-workshop/src/scripts/components/pl-nav/nav-list.scss
  packages/uikit-workshop/src/scripts/components/pl-nav/nav.js
  packages/uikit-workshop/src/scripts/components/pl-nav/nav.scss
  packages/uikit-workshop/src/scripts/components/pl-nav/pl-nav.scss
  packages/uikit-workshop/src/scripts/components/pl-nav/src/NavButton.js
  packages/uikit-workshop/src/scripts/components/pl-nav/src/NavItem.js
  packages/uikit-workshop/src/scripts/components/pl-nav/src/NavLink.js
  packages/uikit-workshop/src/scripts/components/pl-nav/src/NavList.js
  packages/uikit-workshop/src/scripts/components/pl-nav/src/NavTitle.js
  packages/uikit-workshop/src/scripts/components/pl-nav/src/NavToggle.js
  packages/uikit-workshop/src/scripts/components/pl-nav/src/PatternState.js
  packages/uikit-workshop/src/scripts/lit-components/pl-drawer/pl-drawer.js
  packages/uikit-workshop/src/scripts/lit-components/pl-drawer/pl-drawer.scss
  packages/uikit-workshop/src/scripts/patternlab-components.js
  packages/uikit-workshop/webpack.config.js
  yarn.lock
Labels: fix / refactor :construction:, uikit

#1469 feat(docs): added plugin
  packages/docs/src/docs/advanced-ecosystem-overview.md
Labels: documentation :book:

#1475 fix: js error
  packages/uikit-workshop/src/scripts/components/pl-nav/nav.js
  packages/uikit-workshop/src/scripts/lit-components/pl-header/pl-header.js
  packages/uikit-workshop/src/scripts/lit-components/pl-tools-menu/pl-tools-menu.js
Labels: bug :bug:

#1301 refactor: updated devDependencies regarding webpack / to webpack version 5 & some cleanup
  packages/uikit-workshop/build/webpack-server.js
  packages/uikit-workshop/package.json
  packages/uikit-workshop/src/html/index.html
  packages/uikit-workshop/webpack.config.js
  yarn.lock
Labels: dependencies, breaking :exclamation:

#1476 docs: added upgrading guide
  UPGRADE_GUIDE.md
  packages/core/src/lib/pattern_engines.js
Labels: documentation :book:
